/**
 * Correspondance Terminal Linux (Bash) ↔ Invite de commandes Windows (CMD)
 * Design by Grok — pour apprendre Windows en partant de Linux
 */
const COMMANDS = [
  {
    cat: "navigation",
    linux: "pwd",
    win: "cd",
    desc: "Affiche le répertoire courant",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "cd /chemin",
    win: "cd C:\\chemin",
    desc: "Change de répertoire",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "cd ~",
    win: "cd %USERPROFILE%",
    desc: "Aller dans le dossier personnel",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "cd -",
    win: "cd /d %OLDPWD% (limité)",
    desc: "Revenir au répertoire précédent",
  },
  {
    cat: "navigation",
    linux: "ls",
    win: "dir",
    desc: "Liste le contenu du dossier",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "ls -la",
    win: "dir /a",
    desc: "Liste tout, y compris les fichiers cachés",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "ls -lh",
    win: "dir",
    desc: "Liste détaillée (taille lisible côté Linux)",
  },
  {
    cat: "navigation",
    linux: "tree",
    win: "tree",
    desc: "Arborescence des dossiers",
  },
  {
    cat: "fichiers",
    linux: "touch fichier.txt",
    win: "type nul > fichier.txt",
    desc: "Crée un fichier vide",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "mkdir dossier",
    win: "mkdir dossier",
    desc: "Crée un dossier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "mkdir -p a/b/c",
    win: "mkdir a\\b\\c",
    desc: "Crée une arborescence de dossiers",
  },
  {
    cat: "fichiers",
    linux: "cp source dest",
    win: "copy source dest",
    desc: "Copie un fichier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "cp -r dossier/ dest/",
    win: "xcopy dossier dest /E /I  # ou robocopy",
    desc: "Copie récursive d’un dossier",
  },
  {
    cat: "fichiers",
    linux: "mv source dest",
    win: "move source dest",
    desc: "Déplace ou renomme",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "rm fichier",
    win: "del fichier",
    desc: "Supprime un fichier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "rm -rf dossier/",
    win: "rmdir /s /q dossier",
    desc: "Supprime un dossier et son contenu (attention : destructif)",
  },
  {
    cat: "fichiers",
    linux: "cat fichier",
    win: "type fichier",
    desc: "Affiche le contenu d’un fichier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "head -n 20 fichier",
    win: "more fichier (manuel)",
    desc: "Premières lignes d’un fichier",
  },
  {
    cat: "fichiers",
    linux: "tail -n 20 fichier",
    win: "—",
    desc: "Dernières lignes d’un fichier",
  },
  {
    cat: "fichiers",
    linux: "tail -f log.txt",
    win: "—",
    desc: "Suit un fichier en direct (logs)",
  },
  {
    cat: "fichiers",
    linux: "less fichier",
    win: "more fichier",
    desc: "Parcourt un fichier page par page",
  },
  {
    cat: "fichiers",
    linux: "wc -l fichier",
    win: "find /c /v \"\" fichier",
    desc: "Compte les lignes",
  },
  {
    cat: "fichiers",
    linux: "find . -name \"*.txt\"",
    win: "dir /s *.txt",
    desc: "Recherche de fichiers par nom",
  },
  {
    cat: "fichiers",
    linux: "grep \"texte\" fichier",
    win: "findstr \"texte\" fichier",
    desc: "Recherche de texte dans un fichier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "grep -r \"texte\" .",
    win: "findstr /s /i \"texte\" *.*",
    desc: "Recherche récursive de texte",
  },
  {
    cat: "fichiers",
    linux: "ln -s cible lien",
    win: "mklink lien cible",
    desc: "Crée un lien symbolique",
  },
  {
    cat: "fichiers",
    linux: "chmod +x script.sh",
    win: "— (ACL via icacls)",
    desc: "Permissions / autoriser l’exécution",
  },
  {
    cat: "fichiers",
    linux: "diff a.txt b.txt",
    win: "fc a.txt b.txt",
    desc: "Compare deux fichiers",
  },
  {
    cat: "systeme",
    linux: "whoami",
    win: "whoami",
    desc: "Utilisateur connecté",
  },
  {
    cat: "systeme",
    linux: "hostname",
    win: "hostname",
    desc: "Nom de la machine",
  },
  {
    cat: "systeme",
    linux: "uname -a",
    win: "systeminfo | findstr /B /C:\"OS\"",
    desc: "Infos système / OS",
  },
  {
    cat: "systeme",
    linux: "df -h",
    win: "wmic logicaldisk get size,freespace,caption",
    desc: "Espace disque",
  },
  {
    cat: "systeme",
    linux: "du -sh *",
    win: "—",
    desc: "Taille des dossiers",
  },
  {
    cat: "systeme",
    linux: "free -h",
    win: "systeminfo | findstr Mémoire",
    desc: "Mémoire RAM disponible",
  },
  {
    cat: "systeme",
    linux: "top / htop",
    win: "tasklist",
    desc: "Processus en cours (vue top)",
  },
  {
    cat: "systeme",
    linux: "ps aux",
    win: "tasklist",
    desc: "Liste des processus",
    essential: true,
  },
  {
    cat: "systeme",
    linux: "kill PID",
    win: "taskkill /PID PID",
    desc: "Tue un processus par PID",
  },
  {
    cat: "systeme",
    linux: "killall nom",
    win: "taskkill /IM nom.exe /F",
    desc: "Tue un processus par nom",
  },
  {
    cat: "systeme",
    linux: "clear",
    win: "cls",
    desc: "Efface l’écran du terminal",
  },
  {
    cat: "systeme",
    linux: "history",
    win: "doskey /history",
    desc: "Historique des commandes",
  },
  {
    cat: "systeme",
    linux: "sudo commande",
    win: "runas /user:Administrator cmd",
    desc: "Exécuter en administrateur",
  },
  {
    cat: "systeme",
    linux: "reboot",
    win: "shutdown /r /t 0",
    desc: "Redémarre la machine",
  },
  {
    cat: "systeme",
    linux: "shutdown -h now",
    win: "shutdown /s /t 0",
    desc: "Éteint la machine",
  },
  {
    cat: "systeme",
    linux: "date",
    win: "date /t & time /t",
    desc: "Date et heure",
  },
  {
    cat: "systeme",
    linux: "uptime",
    win: "net statistics workstation",
    desc: "Temps depuis le démarrage",
  },
  {
    cat: "reseau",
    linux: "ifconfig / ip a",
    win: "ipconfig",
    desc: "Configuration IP",
  },
  {
    cat: "reseau",
    linux: "ping host",
    win: "ping host",
    desc: "Test de connectivité",
  },
  {
    cat: "reseau",
    linux: "traceroute host",
    win: "tracert host",
    desc: "Trace la route vers un hôte",
  },
  {
    cat: "reseau",
    linux: "netstat -tulpn",
    win: "netstat -ano",
    desc: "Ports et connexions réseau",
  },
  {
    cat: "reseau",
    linux: "curl URL",
    win: "curl URL (Win10+)",
    desc: "Requête HTTP",
  },
  {
    cat: "reseau",
    linux: "wget URL",
    win: "curl -O URL",
    desc: "Télécharge un fichier",
  },
  {
    cat: "reseau",
    linux: "ssh user@host",
    win: "ssh user@host",
    desc: "Connexion SSH distante",
  },
  {
    cat: "reseau",
    linux: "scp file user@host:",
    win: "scp file user@host:",
    desc: "Copie de fichiers via SSH",
  },
  {
    cat: "reseau",
    linux: "nslookup domain",
    win: "nslookup domain",
    desc: "Résolution DNS",
  },
  {
    cat: "env",
    linux: "echo $VAR",
    win: "echo %VAR%",
    desc: "Affiche une variable d’environnement",
    essential: true,
  },
  {
    cat: "env",
    linux: "export VAR=valeur",
    win: "set VAR=valeur",
    desc: "Définit une variable (session)",
  },
  {
    cat: "env",
    linux: "env / printenv",
    win: "set",
    desc: "Liste les variables d’environnement",
  },
  {
    cat: "env",
    linux: "echo $PATH",
    win: "echo %PATH%",
    desc: "Affiche le PATH",
  },
  {
    cat: "env",
    linux: "which commande",
    win: "where commande",
    desc: "Où se trouve une commande",
  },
  {
    cat: "env",
    linux: "alias ll='ls -la'",
    win: "doskey ll=dir $*",
    desc: "Crée un alias",
  },
  {
    cat: "texte",
    linux: "echo \"hello\"",
    win: "echo hello",
    desc: "Affiche du texte",
  },
  {
    cat: "texte",
    linux: "cmd1 | cmd2",
    win: "cmd1 | cmd2",
    desc: "Pipeline (chaîne de commandes)",
  },
  {
    cat: "texte",
    linux: "commande > fichier",
    win: "commande > fichier",
    desc: "Redirige la sortie vers un fichier",
  },
  {
    cat: "texte",
    linux: "commande >> fichier",
    win: "commande >> fichier",
    desc: "Ajoute la sortie à un fichier",
  },
  {
    cat: "texte",
    linux: "commande 2>&1",
    win: "commande 2>&1",
    desc: "Fusionne stderr dans stdout",
  },
  {
    cat: "texte",
    linux: "sort fichier",
    win: "sort fichier",
    desc: "Trie les lignes",
  },
  {
    cat: "texte",
    linux: "uniq",
    win: "—",
    desc: "Lignes uniques",
  },
  {
    cat: "texte",
    linux: "cut -d: -f1",
    win: "for /f \"tokens=1 delims=:\" %i in (...)",
    desc: "Extrait une colonne / champ",
  },
  {
    cat: "texte",
    linux: "sed 's/a/b/g'",
    win: "—",
    desc: "Remplacement de texte",
  },
  {
    cat: "texte",
    linux: "awk '{print $1}'",
    win: "for /f %i in (...)",
    desc: "Traitement de champs",
  },
  {
    cat: "archives",
    linux: "tar -czf archive.tar.gz dossier/",
    win: "tar -czf archive.tar.gz dossier (Win10+)",
    desc: "Crée une archive compressée",
  },
  {
    cat: "archives",
    linux: "tar -xzf archive.tar.gz",
    win: "tar -xzf archive.tar.gz",
    desc: "Extrait une archive",
  },
  {
    cat: "archives",
    linux: "zip -r a.zip dossier/",
    win: "tar -a -cf a.zip dossier",
    desc: "Crée un ZIP",
  },
  {
    cat: "archives",
    linux: "unzip a.zip",
    win: "tar -xf a.zip",
    desc: "Décompresse un ZIP",
  },
  {
    cat: "packages",
    linux: "apt install paquet  # Debian/Ubuntu",
    win: "winget install paquet",
    desc: "Installe un logiciel",
  },
  {
    cat: "packages",
    linux: "apt update && apt upgrade",
    win: "winget upgrade --all",
    desc: "Met à jour les paquets / apps",
  },
  {
    cat: "packages",
    linux: "apt remove paquet",
    win: "winget uninstall paquet",
    desc: "Désinstalle un logiciel",
  },
  {
    cat: "packages",
    linux: "apt search mot",
    win: "winget search mot",
    desc: "Cherche un paquet",
  },
  {
    cat: "packages",
    linux: "dpkg -l / rpm -qa",
    win: "winget list",
    desc: "Liste les logiciels installés",
  },
];

const CATEGORIES = {
  all: { label: "Tout", icon: "spark" },
  navigation: { label: "Navigation", icon: "folder" },
  fichiers: { label: "Fichiers", icon: "file" },
  systeme: { label: "Système", icon: "gear" },
  reseau: { label: "Réseau", icon: "globe" },
  env: { label: "Environnement", icon: "wrench" },
  texte: { label: "Texte & pipe", icon: "pencil" },
  archives: { label: "Archives", icon: "package" },
  packages: { label: "Packages", icon: "download" },
};
