/**
 * Correspondance Linux Bash ↔ PowerShell ↔ CMD
 * Design by Grok — pour apprendre Windows en partant de Linux
 */
const COMMANDS = [
  // ——— Navigation ———
  {
    cat: "navigation",
    linux: "pwd",
    ps: "Get-Location  # ou pwd",
    cmd: "cd",
    desc: "Affiche le répertoire courant",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "cd /chemin",
    ps: "Set-Location C:\\chemin  # ou cd",
    cmd: "cd C:\\chemin",
    desc: "Change de répertoire",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "cd ~",
    ps: "Set-Location $HOME  # ou cd ~",
    cmd: "cd %USERPROFILE%",
    desc: "Aller dans le dossier personnel",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "cd -",
    ps: "Set-Location -  # ou popd / pushd",
    cmd: "cd /d %OLDPWD% (limité)",
    desc: "Revenir au répertoire précédent",
  },
  {
    cat: "navigation",
    linux: "ls",
    ps: "Get-ChildItem  # ou ls, dir, gci",
    cmd: "dir",
    desc: "Liste le contenu du dossier",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "ls -la",
    ps: "Get-ChildItem -Force",
    cmd: "dir /a",
    desc: "Liste tout, y compris les fichiers cachés",
    essential: true,
  },
  {
    cat: "navigation",
    linux: "ls -lh",
    ps: "Get-ChildItem | Format-Table Name, Length, LastWriteTime",
    cmd: "dir",
    desc: "Liste détaillée (taille lisible côté Linux)",
  },
  {
    cat: "navigation",
    linux: "tree",
    ps: "tree  # ou Get-ChildItem -Recurse",
    cmd: "tree",
    desc: "Arborescence des dossiers",
  },

  // ——— Fichiers ———
  {
    cat: "fichiers",
    linux: "touch fichier.txt",
    ps: "New-Item fichier.txt -ItemType File",
    cmd: "type nul > fichier.txt",
    desc: "Crée un fichier vide",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "mkdir dossier",
    ps: "New-Item dossier -ItemType Directory  # ou mkdir",
    cmd: "mkdir dossier",
    desc: "Crée un dossier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "mkdir -p a/b/c",
    ps: "New-Item a\\b\\c -ItemType Directory -Force",
    cmd: "mkdir a\\b\\c",
    desc: "Crée une arborescence de dossiers",
  },
  {
    cat: "fichiers",
    linux: "cp source dest",
    ps: "Copy-Item source dest  # ou cp, copy",
    cmd: "copy source dest",
    desc: "Copie un fichier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "cp -r dossier/ dest/",
    ps: "Copy-Item dossier dest -Recurse",
    cmd: "xcopy dossier dest /E /I  # ou robocopy",
    desc: "Copie récursive d’un dossier",
  },
  {
    cat: "fichiers",
    linux: "mv source dest",
    ps: "Move-Item source dest  # ou mv, move",
    cmd: "move source dest",
    desc: "Déplace ou renomme",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "rm fichier",
    ps: "Remove-Item fichier  # ou rm, del",
    cmd: "del fichier",
    desc: "Supprime un fichier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "rm -rf dossier/",
    ps: "Remove-Item dossier -Recurse -Force",
    cmd: "rmdir /s /q dossier",
    desc: "Supprime un dossier et son contenu (⚠️ destructif)",
  },
  {
    cat: "fichiers",
    linux: "cat fichier",
    ps: "Get-Content fichier  # ou cat, type, gc",
    cmd: "type fichier",
    desc: "Affiche le contenu d’un fichier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "head -n 20 fichier",
    ps: "Get-Content fichier -TotalCount 20  # ou -Head 20",
    cmd: "more fichier (manuel)",
    desc: "Premières lignes d’un fichier",
  },
  {
    cat: "fichiers",
    linux: "tail -n 20 fichier",
    ps: "Get-Content fichier -Tail 20",
    cmd: "—",
    desc: "Dernières lignes d’un fichier",
  },
  {
    cat: "fichiers",
    linux: "tail -f log.txt",
    ps: "Get-Content log.txt -Wait -Tail 20",
    cmd: "—",
    desc: "Suit un fichier en direct (logs)",
  },
  {
    cat: "fichiers",
    linux: "less fichier",
    ps: "Get-Content fichier | more  # ou Out-Host -Paging",
    cmd: "more fichier",
    desc: "Parcourt un fichier page par page",
  },
  {
    cat: "fichiers",
    linux: "wc -l fichier",
    ps: "(Get-Content fichier).Count",
    cmd: "find /c /v \"\" fichier",
    desc: "Compte les lignes",
  },
  {
    cat: "fichiers",
    linux: "find . -name \"*.txt\"",
    ps: "Get-ChildItem -Recurse -Filter *.txt",
    cmd: "dir /s *.txt",
    desc: "Recherche de fichiers par nom",
  },
  {
    cat: "fichiers",
    linux: "grep \"texte\" fichier",
    ps: "Select-String -Path fichier -Pattern \"texte\"  # ou sls",
    cmd: "findstr \"texte\" fichier",
    desc: "Recherche de texte dans un fichier",
    essential: true,
  },
  {
    cat: "fichiers",
    linux: "grep -r \"texte\" .",
    ps: "Select-String -Path * -Pattern \"texte\" -Recurse",
    cmd: "findstr /s /i \"texte\" *.*",
    desc: "Recherche récursive de texte",
  },
  {
    cat: "fichiers",
    linux: "ln -s cible lien",
    ps: "New-Item -ItemType SymbolicLink -Path lien -Target cible",
    cmd: "mklink lien cible",
    desc: "Crée un lien symbolique",
  },
  {
    cat: "fichiers",
    linux: "chmod +x script.sh",
    ps: "Unblock-File script.ps1  # exécution : Set-ExecutionPolicy",
    cmd: "— (ACL via icacls)",
    desc: "Permissions / autoriser l’exécution",
  },
  {
    cat: "fichiers",
    linux: "diff a.txt b.txt",
    ps: "Compare-Object (gc a.txt) (gc b.txt)",
    cmd: "fc a.txt b.txt",
    desc: "Compare deux fichiers",
  },

  // ——— Système ———
  {
    cat: "systeme",
    linux: "whoami",
    ps: "whoami  # ou $env:USERNAME",
    cmd: "whoami",
    desc: "Utilisateur connecté",
  },
  {
    cat: "systeme",
    linux: "hostname",
    ps: "hostname  # ou $env:COMPUTERNAME",
    cmd: "hostname",
    desc: "Nom de la machine",
  },
  {
    cat: "systeme",
    linux: "uname -a",
    ps: "Get-ComputerInfo | Select OsName, OsVersion",
    cmd: "systeminfo | findstr /B /C:\"OS\"",
    desc: "Infos système / OS",
  },
  {
    cat: "systeme",
    linux: "df -h",
    ps: "Get-PSDrive -PSProvider FileSystem",
    cmd: "wmic logicaldisk get size,freespace,caption",
    desc: "Espace disque",
  },
  {
    cat: "systeme",
    linux: "du -sh *",
    ps: "Get-ChildItem | ForEach-Object { $_.Name; (Get-ChildItem $_.FullName -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum }",
    cmd: "—",
    desc: "Taille des dossiers",
  },
  {
    cat: "systeme",
    linux: "free -h",
    ps: "Get-CimInstance Win32_OperatingSystem | Select FreePhysicalMemory, TotalVisibleMemorySize",
    cmd: "systeminfo | findstr Mémoire",
    desc: "Mémoire RAM disponible",
  },
  {
    cat: "systeme",
    linux: "top / htop",
    ps: "Get-Process | Sort-Object CPU -Descending | Select -First 15",
    cmd: "tasklist",
    desc: "Processus en cours (vue top)",
  },
  {
    cat: "systeme",
    linux: "ps aux",
    ps: "Get-Process  # ou gps",
    cmd: "tasklist",
    desc: "Liste des processus",
    essential: true,
  },
  {
    cat: "systeme",
    linux: "kill PID",
    ps: "Stop-Process -Id PID  # ou kill",
    cmd: "taskkill /PID PID",
    desc: "Tue un processus par PID",
  },
  {
    cat: "systeme",
    linux: "killall nom",
    ps: "Stop-Process -Name nom -Force",
    cmd: "taskkill /IM nom.exe /F",
    desc: "Tue un processus par nom",
  },
  {
    cat: "systeme",
    linux: "clear",
    ps: "Clear-Host  # ou cls, clear",
    cmd: "cls",
    desc: "Efface l’écran du terminal",
  },
  {
    cat: "systeme",
    linux: "history",
    ps: "Get-History  # ou history",
    cmd: "doskey /history",
    desc: "Historique des commandes",
  },
  {
    cat: "systeme",
    linux: "sudo commande",
    ps: "Start-Process pwsh -Verb RunAs  # ou Terminal en admin",
    cmd: "runas /user:Administrator cmd",
    desc: "Exécuter en administrateur",
  },
  {
    cat: "systeme",
    linux: "reboot",
    ps: "Restart-Computer",
    cmd: "shutdown /r /t 0",
    desc: "Redémarre la machine",
  },
  {
    cat: "systeme",
    linux: "shutdown -h now",
    ps: "Stop-Computer",
    cmd: "shutdown /s /t 0",
    desc: "Éteint la machine",
  },
  {
    cat: "systeme",
    linux: "date",
    ps: "Get-Date",
    cmd: "date /t & time /t",
    desc: "Date et heure",
  },
  {
    cat: "systeme",
    linux: "uptime",
    ps: "(Get-Date) - (Get-CimInstance Win32_OperatingSystem).LastBootUpTime",
    cmd: "net statistics workstation",
    desc: "Temps depuis le démarrage",
  },

  // ——— Réseau ———
  {
    cat: "reseau",
    linux: "ifconfig / ip a",
    ps: "Get-NetIPAddress  # ou ipconfig",
    cmd: "ipconfig",
    desc: "Configuration IP",
  },
  {
    cat: "reseau",
    linux: "ping host",
    ps: "Test-Connection host  # ou ping",
    cmd: "ping host",
    desc: "Test de connectivité",
  },
  {
    cat: "reseau",
    linux: "traceroute host",
    ps: "Test-NetConnection host -TraceRoute",
    cmd: "tracert host",
    desc: "Trace la route vers un hôte",
  },
  {
    cat: "reseau",
    linux: "netstat -tulpn",
    ps: "Get-NetTCPConnection  # ou netstat -ano",
    cmd: "netstat -ano",
    desc: "Ports et connexions réseau",
  },
  {
    cat: "reseau",
    linux: "curl URL",
    ps: "Invoke-WebRequest URL  # ou curl, iwr",
    cmd: "curl URL (Win10+)",
    desc: "Requête HTTP",
  },
  {
    cat: "reseau",
    linux: "wget URL",
    ps: "Invoke-WebRequest URL -OutFile fichier",
    cmd: "curl -O URL",
    desc: "Télécharge un fichier",
  },
  {
    cat: "reseau",
    linux: "ssh user@host",
    ps: "ssh user@host  # OpenSSH intégré",
    cmd: "ssh user@host",
    desc: "Connexion SSH distante",
  },
  {
    cat: "reseau",
    linux: "scp file user@host:",
    ps: "scp file user@host:  # ou Copy-Item via session",
    cmd: "scp file user@host:",
    desc: "Copie de fichiers via SSH",
  },
  {
    cat: "reseau",
    linux: "nslookup domain",
    ps: "Resolve-DnsName domain  # ou nslookup",
    cmd: "nslookup domain",
    desc: "Résolution DNS",
  },

  // ——— Variables & env ———
  {
    cat: "env",
    linux: "echo $VAR",
    ps: "echo $env:VAR  # ou Write-Output $env:VAR",
    cmd: "echo %VAR%",
    desc: "Affiche une variable d’environnement",
    essential: true,
  },
  {
    cat: "env",
    linux: "export VAR=valeur",
    ps: "$env:VAR = \"valeur\"",
    cmd: "set VAR=valeur",
    desc: "Définit une variable (session)",
  },
  {
    cat: "env",
    linux: "env / printenv",
    ps: "Get-ChildItem Env:",
    cmd: "set",
    desc: "Liste les variables d’environnement",
  },
  {
    cat: "env",
    linux: "echo $PATH",
    ps: "$env:PATH -split ';'",
    cmd: "echo %PATH%",
    desc: "Affiche le PATH",
  },
  {
    cat: "env",
    linux: "which commande",
    ps: "Get-Command commande  # ou where.exe",
    cmd: "where commande",
    desc: "Où se trouve une commande",
  },
  {
    cat: "env",
    linux: "alias ll='ls -la'",
    ps: "Set-Alias ll Get-ChildItem  # ou function",
    cmd: "doskey ll=dir $*",
    desc: "Crée un alias",
  },

  // ——— Texte & pipeline ———
  {
    cat: "texte",
    linux: "echo \"hello\"",
    ps: "Write-Output \"hello\"  # ou echo",
    cmd: "echo hello",
    desc: "Affiche du texte",
  },
  {
    cat: "texte",
    linux: "cmd1 | cmd2",
    ps: "cmd1 | cmd2  # objets, pas seulement du texte",
    cmd: "cmd1 | cmd2",
    desc: "Pipeline (chaîne de commandes)",
  },
  {
    cat: "texte",
    linux: "commande > fichier",
    ps: "commande > fichier  # ou Out-File",
    cmd: "commande > fichier",
    desc: "Redirige la sortie vers un fichier",
  },
  {
    cat: "texte",
    linux: "commande >> fichier",
    ps: "commande >> fichier  # ou Add-Content",
    cmd: "commande >> fichier",
    desc: "Ajoute la sortie à un fichier",
  },
  {
    cat: "texte",
    linux: "commande 2>&1",
    ps: "commande 2>&1  # ou *>&1",
    cmd: "commande 2>&1",
    desc: "Fusionne stderr dans stdout",
  },
  {
    cat: "texte",
    linux: "sort fichier",
    ps: "Get-Content fichier | Sort-Object",
    cmd: "sort fichier",
    desc: "Trie les lignes",
  },
  {
    cat: "texte",
    linux: "uniq",
    ps: "... | Select-Object -Unique",
    cmd: "—",
    desc: "Lignes uniques",
  },
  {
    cat: "texte",
    linux: "cut -d: -f1",
    ps: "... | ForEach-Object { ($_ -split ':')[0] }",
    cmd: "for /f \"tokens=1 delims=:\" %i in (...)",
    desc: "Extrait une colonne / champ",
  },
  {
    cat: "texte",
    linux: "sed 's/a/b/g'",
    ps: "... | ForEach-Object { $_ -replace 'a','b' }",
    cmd: "—",
    desc: "Remplacement de texte",
  },
  {
    cat: "texte",
    linux: "awk '{print $1}'",
    ps: "... | ForEach-Object { ($_ -split '\\s+')[0] }",
    cmd: "for /f %i in (...)",
    desc: "Traitement de champs",
  },

  // ——— Archives ———
  {
    cat: "archives",
    linux: "tar -czf archive.tar.gz dossier/",
    ps: "Compress-Archive -Path dossier -DestinationPath archive.zip",
    cmd: "tar -czf archive.tar.gz dossier (Win10+)",
    desc: "Crée une archive compressée",
  },
  {
    cat: "archives",
    linux: "tar -xzf archive.tar.gz",
    ps: "Expand-Archive archive.zip -DestinationPath .",
    cmd: "tar -xzf archive.tar.gz",
    desc: "Extrait une archive",
  },
  {
    cat: "archives",
    linux: "zip -r a.zip dossier/",
    ps: "Compress-Archive dossier a.zip",
    cmd: "tar -a -cf a.zip dossier",
    desc: "Crée un ZIP",
  },
  {
    cat: "archives",
    linux: "unzip a.zip",
    ps: "Expand-Archive a.zip",
    cmd: "tar -xf a.zip",
    desc: "Décompresse un ZIP",
  },

  // ——— Packages / logiciels ———
  {
    cat: "packages",
    linux: "apt install paquet  # Debian/Ubuntu",
    ps: "winget install paquet  # ou choco install",
    cmd: "winget install paquet",
    desc: "Installe un logiciel",
  },
  {
    cat: "packages",
    linux: "apt update && apt upgrade",
    ps: "winget upgrade --all",
    cmd: "winget upgrade --all",
    desc: "Met à jour les paquets / apps",
  },
  {
    cat: "packages",
    linux: "apt remove paquet",
    ps: "winget uninstall paquet",
    cmd: "winget uninstall paquet",
    desc: "Désinstalle un logiciel",
  },
  {
    cat: "packages",
    linux: "apt search mot",
    ps: "winget search mot",
    cmd: "winget search mot",
    desc: "Cherche un paquet",
  },
  {
    cat: "packages",
    linux: "dpkg -l / rpm -qa",
    ps: "winget list  # ou Get-Package",
    cmd: "winget list",
    desc: "Liste les logiciels installés",
  },
];

const CATEGORIES = {
  all: { label: "Tout", icon: "✦" },
  navigation: { label: "Navigation", icon: "📁" },
  fichiers: { label: "Fichiers", icon: "📄" },
  systeme: { label: "Système", icon: "⚙️" },
  reseau: { label: "Réseau", icon: "🌐" },
  env: { label: "Environnement", icon: "🔧" },
  texte: { label: "Texte & pipe", icon: "✏️" },
  archives: { label: "Archives", icon: "📦" },
  packages: { label: "Packages", icon: "📥" },
};
